from fastapi import APIRouter, Request

router = APIRouter(tags=["metrics"])


@router.get("/metrics/baselines")
async def baselines(request: Request):
    """
    Every number the console shows, and every number in the deck, comes from
    here - which comes from artifacts/*.json, which is written by the training
    scripts. One chain, no hand-typed figures.
    """
    m = request.app.state.engine.metrics
    return {
        "nowcast": m.get("nowcast", {}),
        "intensity": m.get("intensity", {}),
        "provenance": ("Generated by src/cyclops/train/train_nowcast.py and "
                       "train_intensity.py; regenerate with `make train`."),
    }
